### ISSUE TITLE
Review suggestions

### ISSUE THREAD

**Issue by paulvangentcom** [rhenanbartels/hrv#17]
Hi @rhenanbartels,

I was asked to review your submission to JOSS. Some suggestions from my end:

- I think the paper can benefit from additional integration with existing literature, especially a more recent state of the field.

- The software needs to be documented with proper docstrings in the code, I personally recommend either the Numpy or Google style. [see for example docstrings here](https://github.com/numpy/numpy/blob/master/numpy/polynomial/hermite.py)

-  Unit tests are missing, when using Numpy or Google style you can include examples in the docstring that double as unit tests.

- Continuous integration, code coverage metrics, and an overview of the Python versions that are supported is missing too. There's many services out there for unit tests, I personally use travis-ci for CI and codecov.io for coverage results. You can add badges to the repo that update with CI and coverage results for each git push.

Although many toolboxes exist to work with PPG, ECG, or the resulting tachograms, I think _hrv_ can play a nice role as an accessible toolbox for those already having tachograms available and need to analyse these. Congratulations on the work. Please keep me updated on the progress.

\-Paul

**Comment by paulvangentcom** [comment]
One final addition: I suggest adding some demo data to the package and docs, so that everyone can follow along with the quickstart.

**Comment by rhenanbartels** [comment]
Hi @paulvangentcom, thank you very much for the suggestions.

I couldn't agree more. Now it's time to focus on the documentation of the package and CI.

I will work on this issue along the week and send an update when it's done or if I have any doubts.

Best regards,

Rhenan

**Comment by rhenanbartels** [comment]
Hi, @paulvangentcom,

Following your suggestions, I've added some features regarding the documentation:

 - A Docstring for every main function of the submodules
 - Add the project to **travis-ci** and add the badge to README
 - Add the project to **codecov** with **tests** coverage status and its respective badge
 - Add Badge telling the supported Python version
 - Moved the documentation to [readthedocs](https://hrv.readthedocs.io/en/latest/)

Regarding the paper, which improvements would you like to see in order to make it more close to the state of the art?

Thank you very much again for your suggestions. They improved a lot the quality of the hrv module;

Best Regards,

Rhenan

**Comment by paulvangentcom** [comment]
Hi @rhenanbartels,

Thanks for the work. The docs look nice and I think everything improved markedly!

For the paper, what I'm missing is:
- What other software is there and how is hrv different/complementary to what is there? A brief overview woudl suffice.
- The statement of need can be stronger: right now at the end of the summary section you describe what the software does, not why it's needed. I think the statement of need will flow naturally from the first point on overview of software.
- The nonlinear section is too brief. Describe what you're expressing (perhaps together with a plot): the standard deviation along and perpendicular to the identity line on an RR-plot. With poincare it's also customary to compute 's' (area of the ellipse described by sd1, sd2), and the sd1/sd2 ratio. As long as you link to the source, you can [nick the method here](https://github.com/paulvangentcom/heartrate_analysis_python/blob/master/heartpy/analysis.py#L637), and the [plotting method here](https://github.com/paulvangentcom/heartrate_analysis_python/blob/master/heartpy/visualizeutils.py#L189).

Good luck with the final touches!

-Paul

**Comment by paulvangentcom** [comment]
Thanks for all the updates Rhenan. I think it improved a lot.

Two final comments:
- The community guidelines on the docs on how to contribute now only outline the creation of a virtualenv. Including something about things like the preferred coding style, docstring style, and module structure might help people starting out with contributing.
- You link to the repo for HeartPy. We prefer you link to [our software paper instead](https://openresearchsoftware.metajnl.com/articles/10.5334/jors.241/) as it contains more background info.

Cheers,
Paul

**Comment by rhenanbartels** [comment]
Hi @paulvangentcom, I've just implemented the suggestion you've made.

 - I've Created a section telling what is the preferred docstring styles. It is still simple, but it will improve as the project evolves.

 - I've Changed the citation's link to HeartPy. By the way, it is a very nice article.

Thank you very much!

Cheers,

Rhenan
