### ISSUE TITLE
Poincaré Plot and frequency domain analysis problem

### ISSUE THREAD

**Issue by echocherish** [rhenanbartels/hrv#19]
Hi there,
Sorry to take your time and I've two questions.
First of all, my environment is Google's colab, I just use pip to install your HRV package.
1. I want to depict the Poincaré Plot, but I received this error.
![庞加莱图](https://user-images.githubusercontent.com/40596525/82832714-76289e80-9eee-11ea-966c-6e4ec6cf282f.png)

2. When I do frequency analysis, I got this problem.
![频域](https://user-images.githubusercontent.com/40596525/82832887-1088e200-9eef-11ea-8a2f-5b39c319374b.png)

But the time domain analysis works well, so I'm really confused.
![时域](https://user-images.githubusercontent.com/40596525/82832901-1979b380-9eef-11ea-84a7-7803e6e086ff.png)

**Comment by echocherish** [comment]
Thank you !!! And I just solved the problems by using the RRi object.
Thank you for your time !

**Comment by rhenanbartels** [comment]
Hi @echocherish, I am glad that it worked!

Let me know if I can help with anything else.

Cheers!
