### ISSUE TITLE
'pip install' installs very old version

### ISSUE THREAD

**Issue by vivek-bhanuprakash** [rhenanbartels/hrv#9]
Python package repository has an old version of the hrv package.  Any update on when the latest release will be pushed so that 'pip install' picks up the latest version?

Appreciate the time and efforts you put in in making this package.

Thanks!

**Comment by rhenanbartels** [comment]
Hi folks!

Sorry for my mistake. I've already updated the hrv package in PyPI. It is now in 0.1.5 version.

Thank you very much for your feedback.

Truly yours,

Rhenan Bartels
